version: "3.6"

services:

  short-url:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/tmp
    networks:
      - app
    expose:
      # zookeeper
      - "2181"
      #tomcat
      - "8080"
      
    ports:
      
      - "8080:8080"
      - "2181:2181"
    depends_on:
      - "zoo1"
      - "zoo2"
      - "zoo3"
    restart: always
  #zookeepers
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - app

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - app

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - app
      
networks:
  app:
     driver: bridge
      